INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Espada laser', 'Evaluar la fabricacion de una espada laser ', '2018-01-02','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Funciones lineales', 'Introduccion a las funciones lineales', '2020-6-24','Matematicas','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mini prusa', 'Puesta en marcha impresora 3d mini prusa', '2020-03-21','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Molde para maceta octogeo', 'Diseño Cad', '2020-10-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mascarilla Covid-19', 'Desarrollo y produccion de mascarillas',  '2020-4-6','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Clon chino prusa', 'Armado del clon chino prusa', '2021-3-1','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Reconocimiento de imagenes', 'Evaluar el uso del procesador K210 con AI', '2020-12-18','Inteligencia artificial','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Repuesto para piano', 'Prueba del prototipo del repuesto para piano',  '2021-3-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Software y App', 'Uso de lenguajes python, java, Js(react, Vue)',  '2022-3-22','Programacion','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Viga simplemente apoyada', 'Proyecto final universitario',  '2021-11-13','Integrador','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Remote Lab Lib', 'Practica profesional supervisada universitaria',  '2022-4-3','Electronica-Software','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Espada laser1', 'Evaluar la fabricacion de una espada laser ', '2018-01-02','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Funciones 2', 'Introduccion a las funciones lineales', '2020-6-24','Matematicas','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mini 2', 'Puesta en marcha impresora 3d mini prusa', '2020-03-21','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Molde par2a maceta octogeo', 'Diseño Cad', '2020-10-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mascaril2la Covid-19', 'Desarrollo y produccion de mascarillas',  '2020-4-6','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Clon ch3ino prusa', 'Armado del clon chino prusa', '2021-3-1','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Reconocim4iento de imagenes', 'Evaluar el uso del procesador K210 con AI', '2020-12-18','Inteligencia artificial','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Repue5sto para piano', 'Prueba del prototipo del repuesto para piano',  '2021-3-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Soft6ware y App', 'Uso de lenguajes python, java, Js(react, Vue)',  '2022-3-22','Programacion','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Viga7 simplemente apoyada', 'Proyecto final universitario',  '2021-11-13','Integrador','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Remo7te Lab Lib', 'Practica profesional supervisada universitaria',  '2022-4-3','Electronica-Software','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Espad1a laser', 'Evaluar la fabricacion de una espada laser', '2018-01-02','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Funcion1es lineales', 'Introduccion a las funciones lineales', '2020-6-24','Matematicas','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mini pr2usa', 'Puesta en marcha impresora 3d mini prusa', '2020-03-21','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Molde pa2ra maceta octogeo', 'Diseño Cad', '2020-10-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mascaril3la Covid-19', 'Desarrollo y produccion de mascarillas',  '2020-4-6','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Clon ch7ino prusa', 'Armado del clon chino prusa', '2021-3-1','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Reconoci4miento de imagenes', 'Evaluar el uso del procesador K210 con AI', '2020-12-18','Inteligencia artificial','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Repuesto5 para piano', 'Prueba del prototipo del repuesto para piano',  '2021-3-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Softwar5e y App', 'Uso de lenguajes python, java, Js(react, Vue)',  '2022-3-22','Programacion','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Viga si6mplemente apoyada', 'Proyecto final universitario',  '2021-11-13','Integrador','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Remote 1Lab Lib', 'Practica profesional supervisada universitaria',  '2022-4-3','Electronica-Software','educacion.ta@gmail.com');
