INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Espada laser', 'Evaluar la fabricacion de una espada laser electronica', '2018-01-02','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Funciones lineales', 'Introduccion a las funciones lineales', '2020-6-24','Matematicas','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mini prusa', 'Puesta en marcha impresora 3d mini prusa', '2020-03-21','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Molde para maceta octogeo', 'Diseño Cad', '2020-10-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Mascarilla Covid-19', 'Desarrollo y produccion de mascarillas',  '2020-4-6','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Clon chino prusa', 'Armado del clon chino prusa', '2021-3-1','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Reconocimiento de imagenes', 'Evaluar el uso del procesador K210 con AI', '2020-12-18','Inteligencia artificial','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Repuesto para piano', 'Prueba del prototipo del repuesto para piano privia-120',  '2021-3-4','Impresion 3d','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Software y App', 'Uso de lenguajes python, java, Js(react, Vue)',  '2022-3-22','Programacion','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Viga simplemente apoyada', 'Proyecto final universitario',  '2021-11-13','Integrador','educacion.ta@gmail.com');
INSERT INTO proyects (name, intention,  create_at, technology, email ) VALUES('Remote Lab Lib', 'Practica profesional supervisada universitaria',  '2022-4-3','Electronica-Software','educacion.ta@gmail.com');
